sidebar:
  menu:
    home: '[btn.home](/)'
    czbzyfmsx: '[全装备最优附魔顺序](/all-gear-best-enchant-order)'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/brands/github.svg"/>'
      url: https://github.com/MC-HMU
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/solid/envelopes-bulk.svg"/>'
      url: mailto:admin@mc.hmu.ac.cn
  sitemap:
    '主页':
      - '[简介](/)'
      - '[服务器事件记录](/#服务器事件记录)'
      - '[全装备最优附魔顺序](/all-gear-best-enchant-order)'
    '论坛':
      - '[论坛主页](https://bbs.mc.hmu.ac.cn)'
      - '[申请审核帖](https://bbs.mc.hmu.ac.cn/d/3)'

  source: '[GitHub](https://github.com/MC-HMU/website/)'

comments:
  service: utterances # utterances
  utterances:
    repo: Cubik65536/blog-comments

######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true
